FROM node:9.9.0-alpine

USER node

# Create app directory
RUN mkdir -p /home/node/app
WORKDIR /home/node/app

# Install app dependencies
COPY --chown=node:node package.json /home/node/app/
RUN npm install

RUN  yarn add serve
# Bundle app source
COPY --chown=node:node . /home/node/app

ENV REACT_APP_BASE_URL "https://social-media.xenon.work/api"
# Build
RUN npm run build

EXPOSE 5000

ENTRYPOINT ["./node_modules/.bin/serve", "-s", "build"]
