export const PIE_CHART_TITLE_CONFIG = 'PIE_CHART_TITLE_CONFIG';
export const PIE_CHART_SUB_TITLE_CONFIG = 'PIE_CHART_SUB_TITLE_CONFIG';
export const PIE_CHART_SERIES_TYPE_CONFIG = 'PIE_CHART_SERIES_TYPE_CONFIG';
